In [1]:
from transformers import GPT2Tokenizer, TFGPT2LMHeadModel
import tensorflow as tf
# Hide GPU from visible devices
tf.config.set_visible_devices([], 'GPU')
tokenizer = GPT2Tokenizer.from_pretrained('distilgpt2')

In [2]:
model = TFGPT2LMHeadModel.from_pretrained('distilgpt2',pad_token_id=tokenizer.eos_token_id)

All PyTorch model weights were used when initializing TFGPT2LMHeadModel.

All the weights of TFGPT2LMHeadModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [3]:
text = "plaing guitar is a"
encoded_input = tokenizer(text, return_tensors='tf')
encoded_input
# encoded_input.input_ids
# encoded_input.attention_mask

{'input_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[  489,    64,   278, 10047,   318,   257]])>, 'attention_mask': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1]])>}

In [4]:

output = model.generate(
    **encoded_input, 
    max_new_tokens=40,
    temperature=0.7,
    # num_beams=5,
    no_repeat_ngram_size=2,
    # num_return_sequences=5,
    early_stopping=True,
    do_sample=True,
    top_k=50,
    top_p=0.95,
)

In [6]:
output[0]

<tf.Tensor: shape=(44,), dtype=int32, numpy=
array([  489,    64,   278, 10047,   318,   257,   845,  3665, 10047,
          13,   632,   318,   407,   655,   257, 10047,    11,   340,
         318,   635,   257,   922,  8875,   329,  8680,   284,   262,
        2647,    13,   383, 10047,   468,   257,  1049,  2694,   284,
         711, 10047,   290,   318,   845, 21362,    13, 50256])>

In [7]:
tokenizer.decode(output[0])

'plaing guitar is a very powerful guitar. It is not just a guitar, it is also a good instrument for listening to the music. The guitar has a great ability to play guitar and is very versatile.<|endoftext|>'