In [1]:
from transformers import GPT2Tokenizer, TFGPT2LMHeadModel
import tensorflow as tf
# Hide GPU from visible devices
tf.config.set_visible_devices([], 'GPU')
tokenizer = GPT2Tokenizer.from_pretrained('distilgpt2')

In [2]:
model = TFGPT2LMHeadModel.from_pretrained('distilgpt2',pad_token_id=tokenizer.eos_token_id)

All PyTorch model weights were used when initializing TFGPT2LMHeadModel.

All the weights of TFGPT2LMHeadModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [24]:
text = "plaing guitar is a"
encoded_input = tokenizer(text, return_tensors='tf')
encoded_input
# encoded_input.input_ids
# encoded_input.attention_mask

{'input_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[  489,    64,   278, 10047,   318,   257]])>, 'attention_mask': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1]])>}

In [13]:

output = model.generate(
    **encoded_input, 
    max_new_tokens=40,
    temperature=0.7,
    # num_beams=5,
    no_repeat_ngram_size=2,
    # num_return_sequences=5,
    early_stopping=True,
    do_sample=True,
    top_k=50,
    top_p=0.95,
)

In [14]:
output

<tf.Tensor: shape=(1, 46), dtype=int32, numpy=
array([[  489,    64,   278, 10047,   318,   257,  1049,   835,   284,
         1037,   661,  2193,    13,   632,   338,  1327,   284,   651,
          973,   284,   340,    11,   475,   340,   338,   635,  1257,
          284,  2193,     0,   198,   198,  1212,  1281,   318,   636,
          286,   262, 17404, 13815, 45336,    12, 15419, 48401,    12,
         2949]])>

In [15]:
tokenizer.decode(output[0])

"plaing guitar is a great way to help people learn. It's hard to get used to it, but it's also fun to learn!\n\nThis post is part of the Creative Commons Attribution-NonCommercial-No"